{
  "Name": "CurseClient",
  "Process": "Curse.Agent.Host",
  "PID": 2169,
  "Arguments": [
    "/tmp/.mount_CurseFtI9PWl/resources/app.asar.unpacked/plugins/curse/linux/Curse.Agent.Host",
    "--port=51512",
    "--to-port=51532",
    "--pid=1906",
    "--appDataPath=/home/avery/.config/CurseForge",
    "--clientId=Overwolf"
  ],
  "ProcessStart": "2025-06-12T16:29:59.1686902Z",
  "Version": "1.279.0.26201",
  "BuildDate": "2000-01-01T19:33:22Z",
  "Start": "2025-06-12T12:30:00.5856018-04:00",
  "Log": [
{
  "timestamp": "2025-06-12T12:30:00.5651643-04:00",
  "level": "Warn",
  "thread": 1,
  "memory": 0.0,
  "message": "Failed to modified BuiltInConverters: Cannot set initonly static field 'BuiltInConverters' after type 'Newtonsoft.Json.Serialization.DefaultContractResolver' is initialized."
},
{
  "timestamp": "2025-06-12T12:30:00.5794323-04:00",
  "level": "Info",
  "thread": 1,
  "memory": 0.0,
  "message": "Startup Name: CurseForge, Version: 1.279.0.26201"
},
{
  "timestamp": "2025-06-12T12:30:00.5809815-04:00",
  "level": "Info",
  "thread": 1,
  "memory": 0.0,
  "message": "Running Mods Agent with args: --port=51512,--to-port=51532,--pid=1906,--appDataPath=/home/avery/.config/CurseForge,--clientId=Overwolf"
},
{
  "timestamp": "2025-06-12T12:30:00.5905048-04:00",
  "level": "Info",
  "thread": 1,
  "memory": 0.0,
  "message": "start monitor process: 1906"
},
{
  "timestamp": "2025-06-12T12:30:02.7095686-04:00",
  "level": "Info",
  "thread": 1,
  "memory": 0.0,
  "message": "Unable to load game instances from disk. No file was found at: /home/avery/.config/CurseForge/agent/GameInstances/ModpackGameInstances.json"
},
{
  "timestamp": "2025-06-12T12:30:02.9762219-04:00",
  "level": "Info",
  "thread": 1,
  "memory": 0.0,
  "message": "Mods Agent server started on port 51512"
},
{
  "timestamp": "2025-06-12T12:30:03.0714989-04:00",
  "level": "Info",
  "thread": 6,
  "memory": 0.0,
  "message": "Web Socket session connected"
},
{
  "timestamp": "2025-06-12T12:30:03.4004625-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Update simultaneous downloads '1' => '3'"
},
{
  "timestamp": "2025-06-12T12:30:03.4093733-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Initializing Curse Mods Agent"
},
{
  "timestamp": "2025-06-12T12:30:03.4138731-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "update client Info ''..."
},
{
  "timestamp": "2025-06-12T12:30:03.8994806-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:30:03.9464839-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "AddonServiceClient - CfCore Url: https://api.curseforge.com"
},
{
  "timestamp": "2025-06-12T12:30:04.1149089-04:00",
  "level": "Warn",
  "thread": 13,
  "memory": 0.0,
  "message": "Service call failed to: legacy/game/timestamp",
  "error": {
    "message": "Connection refused (api.curseforge.com:443)",
    "type": "System.Net.Http.HttpRequestException",
    "stack": [
      "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "Curse.Server.Communication.ServicesConfiguration.LogWarning(Exception,String)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object,Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused",
      "type": "System.Net.Sockets.SocketException",
      "stack": [
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:04.1701578-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games database timestamp from server. Request failed with status code InternalServerError"
},
{
  "timestamp": "2025-06-12T12:30:04.1726793-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games database timestamp from server",
  "error": {
    "message": "Failed to get games timestamp from server",
    "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
    "stack": [
      "Curse.TechService.AddonServiceClient+<GetGameDatabaseTimestampAsync>d__31.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.TechService.Games.GameRepository+<GetServiceTimestampAsync>d__14.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "Curse.TechService.AddonServiceClient+<GetGameDatabaseTimestampAsync>d__31.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task`1.TrySetResult(TResult)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1,TResult)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object,Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ]
  }
},
{
  "timestamp": "2025-06-12T12:30:04.1847467-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on GameDatabase -> GetRemoteItems"
},
{
  "timestamp": "2025-06-12T12:30:04.1864717-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Getting Games from server"
},
{
  "timestamp": "2025-06-12T12:30:04.2008605-04:00",
  "level": "Warn",
  "thread": 13,
  "memory": 0.0,
  "message": "Service call failed to: legacy/game?supportsAddons=true",
  "error": {
    "message": "Connection refused (api.curseforge.com:443)",
    "type": "System.Net.Http.HttpRequestException",
    "stack": [
      "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "Curse.Server.Communication.ServicesConfiguration.LogWarning(Exception,String)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishContinuations()",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(Object,Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused",
      "type": "System.Net.Sockets.SocketException",
      "stack": [
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:04.2038763-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games from server. Request failed with status code InternalServerError"
},
{
  "timestamp": "2025-06-12T12:30:07.4506315-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:30:07.4576003-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:30:09.2067355-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on GameDatabase -> GetRemoteItems"
},
{
  "timestamp": "2025-06-12T12:30:09.2069189-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Getting Games from server"
},
{
  "timestamp": "2025-06-12T12:30:09.2403423-04:00",
  "level": "Warn",
  "thread": 13,
  "memory": 0.0,
  "message": "Service call failed to: legacy/game?supportsAddons=true",
  "error": {
    "message": "Connection refused (api.curseforge.com:443)",
    "type": "System.Net.Http.HttpRequestException",
    "stack": [
      "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "Curse.Server.Communication.ServicesConfiguration.LogWarning(Exception,String)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused",
      "type": "System.Net.Sockets.SocketException",
      "stack": [
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:09.2518575-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games from server. Request failed with status code InternalServerError"
},
{
  "timestamp": "2025-06-12T12:30:19.2559293-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games from server",
  "error": {
    "message": "One or more errors occurred. (Failed to get games from server) (Failed to get games from server)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.TechService.Games.GameRepository+<GetRemoteItemsAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishStageThree()",
      "System.Threading.Tasks.Task.FinishStageTwo()",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.Finish(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task+DelayPromise.CompleteTimedOut()",
      "System.Threading.TimerQueueTimer.Fire(Boolean)",
      "System.Threading.TimerQueue.FireNextTimers()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed to get games from server",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient+<GetGamesAsync>d__30.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.TechService.Games.GameRepository+<<GetRemoteItemsAsync>b__16_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:19.2665054-04:00",
  "level": "Warn",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed getting games list from server. Attempting to load from local cache"
},
{
  "timestamp": "2025-06-12T12:30:19.267282-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Loading games from local cache at /home/avery/.config/CurseForge/agent/gamesCache.json"
},
{
  "timestamp": "2025-06-12T12:30:19.4835855-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Loaded 25 games from the local games cache"
},
{
  "timestamp": "2025-06-12T12:30:19.503522-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "[GameRepository] Completed download of cache",
  "data": {
    "name": "Games",
    "elapsedTime": "15,303.00"
  }
},
{
  "timestamp": "2025-06-12T12:30:19.5478429-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing local databases..."
},
{
  "timestamp": "2025-06-12T12:30:19.5486807-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing game instances."
},
{
  "timestamp": "2025-06-12T12:30:19.5830336-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Found RegisterType on Type: 'Curse.Radium.Addons.AddonGameInstance'"
},
{
  "timestamp": "2025-06-12T12:30:19.5839165-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Found RegisterType on Type: 'Curse.Games.Minecraft.MinecraftGameInstance'"
},
{
  "timestamp": "2025-06-12T12:30:19.5844132-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing game instance of type Curse.Radium.Addons.AddonGameInstance"
},
{
  "timestamp": "2025-06-12T12:30:19.6765954-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "[AddonGameInstance] LoadInstancesFromDisk loaded 0 instances"
},
{
  "timestamp": "2025-06-12T12:30:19.6768068-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing game instance of type Curse.Games.Minecraft.MinecraftGameInstance"
},
{
  "timestamp": "2025-06-12T12:30:20.4033804-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "[MinecraftGameInstance] LoadInstancesFromDisk loaded 2 instances"
},
{
  "timestamp": "2025-06-12T12:30:20.4166385-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Game Minecraft (Id: 432) was detected at /home/avery/Documents/curseforge/minecraft/Instances/e/"
},
{
  "timestamp": "2025-06-12T12:30:20.5124578-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initialized game e instance"
},
{
  "timestamp": "2025-06-12T12:30:20.5125513-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Game Minecraft (Id: 432) was detected at /home/avery/Documents/curseforge/minecraft/Instances/Homestead - A Cozy Survival Experience/"
},
{
  "timestamp": "2025-06-12T12:30:20.549624-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initialized game Homestead - A Cozy Survival Experience instance"
},
{
  "timestamp": "2025-06-12T12:30:20.5532323-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Game instances initialization completed. Operation took 1002 ms"
},
{
  "timestamp": "2025-06-12T12:30:20.5559116-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing Modpack instances."
},
{
  "timestamp": "2025-06-12T12:30:20.5638399-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #1 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:30:22.3770772-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:30:22.3843327-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:30:25.590123-04:00",
  "level": "Info",
  "thread": 6,
  "memory": 0.0,
  "message": "Attempt #2 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:30:35.6127944-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #3 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:30:45.6335385-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "UpdateCache Exception!",
  "error": {
    "message": "One or more errors occurred. (Connection refused (api.curseforge.com:443)) (Connection refused (api.curseforge.com:443)) (Connection refused (api.curseforge.com:443))",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
      "Curse.Radium.Addons.ProjectRepository+<UpdateProjectsAsync>d__22.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task+DelayPromise.CompleteTimedOut()",
      "System.Threading.TimerQueueTimer.Fire(Boolean)",
      "System.Threading.TimerQueue.FireNextTimers()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused (api.curseforge.com:443)",
      "type": "System.Net.Http.HttpRequestException",
      "stack": [
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
        "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
        "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Server.Communication.BaseWebServiceClient+<PostAsync>d__15`1.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.TechService.AddonServiceClient+<GetProjectsAsync>d__11.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass22_0+<<UpdateProjectsAsync>b__0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
        "Curse.Radium.Utilities.Retry+<>c__DisplayClass4_0+<<DoAsync>b__0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()"
      ],
      "innerError": {
        "message": "Connection refused",
        "type": "System.Net.Sockets.SocketException",
        "stack": [
          "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
          "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
          "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
          "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
          "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
          "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
          "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
        ]
      }
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:45.6897253-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Running startup game detection"
},
{
  "timestamp": "2025-06-12T12:30:45.6989698-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Performing quick game detection for 25 games..."
},
{
  "timestamp": "2025-06-12T12:30:45.7146759-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Completed startup game detection. We have a total of 2 detected game instances. Operation took 24 ms"
},
{
  "timestamp": "2025-06-12T12:30:45.7184605-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:30:45.7194982-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:30:45.801259-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Setting file watcher on instance directory /home/avery/Documents/curseforge/minecraft/Instances"
},
{
  "timestamp": "2025-06-12T12:30:45.8196918-04:00",
  "level": "Warn",
  "thread": 11,
  "memory": 0.0,
  "message": "Service call failed to: v1/minecraft/modloader/timestamp",
  "error": {
    "message": "Connection refused (api.curseforge.com:443)",
    "type": "System.Net.Http.HttpRequestException",
    "stack": [
      "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "Curse.Server.Communication.ServicesConfiguration.LogWarning(Exception,String)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused",
      "type": "System.Net.Sockets.SocketException",
      "stack": [
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:45.823958-04:00",
  "level": "Error",
  "thread": 11,
  "memory": 0.0,
  "message": "Failed getting modloaders database timestamp from server. Request failed with status code InternalServerError"
},
{
  "timestamp": "2025-06-12T12:30:45.8252499-04:00",
  "level": "Error",
  "thread": 11,
  "memory": 0.0,
  "message": "Failed getting modloaders database timestamp from server",
  "error": {
    "message": "Failed to get modloaders timestamp from server",
    "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
    "stack": [
      "Curse.TechService.AddonServiceClient+<GetModloadersDatabaseTimestampAsync>d__27.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Games.Minecraft.ModLoader.ModLoaderRepository+<GetServiceTimestampAsync>d__17.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "Curse.TechService.AddonServiceClient+<GetModloadersDatabaseTimestampAsync>d__27.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task`1.TrySetResult(TResult)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1,TResult)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ]
  }
},
{
  "timestamp": "2025-06-12T12:30:45.8432844-04:00",
  "level": "Info",
  "thread": 11,
  "memory": 0.0,
  "message": "Refreshing Minecraft instances list"
},
{
  "timestamp": "2025-06-12T12:30:45.845326-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing tasks"
},
{
  "timestamp": "2025-06-12T12:30:45.8479105-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Resolving Minecraft instances list from /home/avery/Documents/curseforge/minecraft/Instances"
},
{
  "timestamp": "2025-06-12T12:30:45.8516482-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Skipping existing minecraft game instance at /home/avery/Documents/curseforge/minecraft/Instances/e"
},
{
  "timestamp": "2025-06-12T12:30:45.8517276-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Skipping existing minecraft game instance at /home/avery/Documents/curseforge/minecraft/Instances/Homestead - A Cozy Survival Experience"
},
{
  "timestamp": "2025-06-12T12:30:45.8531202-04:00",
  "level": "Warn",
  "thread": 11,
  "memory": 0.0,
  "message": "Service call failed to: v1/minecraft/modloader?includeAll=true",
  "error": {
    "message": "Connection refused (api.curseforge.com:443)",
    "type": "System.Net.Http.HttpRequestException",
    "stack": [
      "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Threading.Tasks.ValueTask`1.get_Result()",
      "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "Curse.Server.Communication.ServicesConfiguration.LogWarning(Exception,String)",
      "Curse.Server.Communication.BaseWebServiceClient+<GetAsync>d__14`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Threading.Tasks.Task.TrySetException(Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception)",
      "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread)",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused",
      "type": "System.Net.Sockets.SocketException",
      "stack": [
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
        "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:45.8559337-04:00",
  "level": "Error",
  "thread": 11,
  "memory": 0.0,
  "message": "Failed getting Minecraft Modloaders from server. Request failed with status code InternalServerError"
},
{
  "timestamp": "2025-06-12T12:30:45.8620095-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Attempt #1 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:30:45.8626981-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Discord RPC client initialized successfully."
},
{
  "timestamp": "2025-06-12T12:30:45.863017-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Initializing Periodic Tasks"
},
{
  "timestamp": "2025-06-12T12:30:45.9002101-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:30:45.9002484-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:30:46.3892668-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:30:46.3892971-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:30:47.229213-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:30:47.2292465-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:30:47.2235482-04:00",
  "level": "Error",
  "thread": 2,
  "memory": 0.0,
  "message": "Global Unhandled Exception",
  "data": {
    "Exception": {
      "Type": "System.AggregateException",
      "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Failed to get Minecraft Modloaders from server)",
      "Inner": {
        "Type": "Curse.Server.Communication.Exceptions.ServerRequestException",
        "Message": "Failed to get Minecraft Modloaders from server",
        "Stack": [
          "Curse.TechService.AddonServiceClient+<GetModloadersAsync>d__26.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
          "Curse.Games.Minecraft.ModLoader.ModLoaderRepository+<GetRemoteItemsAsync>d__21.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
          "Curse.Radium.Addons.BaseAddonServiceDatabase`3+<UpdateCacheAsync>d__14.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
          "Curse.Radium.Addons.BaseAddonServiceDatabase`3+<InitializeAsync>d__8.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
          "Curse.AppService.MinecraftAppService+<<InitializeAsync>b__22_0>d.MoveNext()"
        ]
      }
    }
  },
  "error": {
    "message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Failed to get Minecraft Modloaders from server)",
    "type": "System.AggregateException",
    "innerError": {
      "message": "Failed to get Minecraft Modloaders from server",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient+<GetModloadersAsync>d__26.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Games.Minecraft.ModLoader.ModLoaderRepository+<GetRemoteItemsAsync>d__21.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Addons.BaseAddonServiceDatabase`3+<UpdateCacheAsync>d__14.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
        "Curse.Radium.Addons.BaseAddonServiceDatabase`3+<InitializeAsync>d__8.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
        "Curse.AppService.MinecraftAppService+<<InitializeAsync>b__22_0>d.MoveNext()"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:30:47.2455698-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:30:49.7216938-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:30:49.7266892-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:30:50.8798379-04:00",
  "level": "Info",
  "thread": 11,
  "memory": 0.0,
  "message": "Attempt #2 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:30:52.3195832-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:00.898029-04:00",
  "level": "Info",
  "thread": 11,
  "memory": 0.0,
  "message": "Attempt #3 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:31:02.3390786-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.Tasks.Task+<>c.<.cctor>b__281_0(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:31:02.3862908-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:02.7213499-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:02.7300828-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:07.4000886-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:08.970552-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:08.9791202-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:10.9094351-04:00",
  "level": "Error",
  "thread": 16,
  "memory": 0.0,
  "message": "UpdateCache Exception!",
  "error": {
    "message": "One or more errors occurred. (Connection refused (api.curseforge.com:443)) (Connection refused (api.curseforge.com:443)) (Connection refused (api.curseforge.com:443))",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
      "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
      "Curse.Radium.Addons.ProjectRepository+<UpdateProjectsAsync>d__22.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task.FinishSlow(Boolean)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception,Task`1&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception)",
      "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(Thread)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext()",
      "System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox,Boolean)",
      "System.Threading.Tasks.Task.RunContinuations(Object)",
      "System.Threading.Tasks.Task+DelayPromise.CompleteTimedOut()",
      "System.Threading.TimerQueueTimer.Fire(Boolean)",
      "System.Threading.TimerQueue.FireNextTimers()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Connection refused (api.curseforge.com:443)",
      "type": "System.Net.Http.HttpRequestException",
      "stack": [
        "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<ConnectAsync>d__103.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__105.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__79.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
        "System.Threading.Tasks.TaskCompletionSourceWithCancellation`1+<WaitWithCancellationAsync>d__1.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Threading.Tasks.ValueTask`1.get_Result()",
        "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult()",
        "System.Net.Http.DecompressionHandler+<SendAsync>d__16.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult()",
        "System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Server.Communication.BaseWebServiceClient+<PostAsync>d__15`1.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.TechService.AddonServiceClient+<GetProjectsAsync>d__11.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass22_0+<<UpdateProjectsAsync>b__0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter.GetResult()",
        "Curse.Radium.Utilities.Retry+<>c__DisplayClass4_0+<<DoAsync>b__0>d.MoveNext()",
        "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
        "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
        "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
        "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()",
        "Curse.Radium.Utilities.Retry+<DoAsync>d__5`1.MoveNext()"
      ],
      "innerError": {
        "message": "Connection refused",
        "type": "System.Net.Sockets.SocketException",
        "stack": [
          "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError,CancellationToken)",
          "System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)",
          "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
          "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
          "System.Net.Sockets.Socket+<<ConnectAsync>g__WaitForConnectWithCancellation|285_0>d.MoveNext()",
          "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()",
          "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)",
          "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task,ConfigureAwaitOptions)",
          "System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()",
          "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()",
          "System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__104.MoveNext()"
        ]
      }
    }
  }
},
{
  "timestamp": "2025-06-12T12:31:13.0635411-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:13.0709022-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:13.927702-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network address has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:13.9338875-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:17.5145914-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Addon()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Author()",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.Tasks.Task+<>c.<.cctor>b__281_0(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:31:17.5164063-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:19.2987519-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:19.3061538-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:22.5392498-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:32.5616995-04:00",
  "level": "Error",
  "thread": 13,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Addon()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_UpdateFileID()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_UpdateAvailable()",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.Tasks.Task+<>c.<.cctor>b__281_0(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:31:32.6214158-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:31:32.6214455-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:31:32.9150762-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:37.9329981-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:47.947891-04:00",
  "level": "Error",
  "thread": 8,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:31:47.9493123-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:50.1335257-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:50.1411091-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:31:52.9658055-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:31:55.4512172-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:31:55.4565054-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:03.3209443-04:00",
  "level": "Error",
  "thread": 8,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Addon()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Author()",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:32:03.3215421-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:32:05.4752906-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:05.4813496-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:08.3453162-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:32:11.9503442-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:11.9579844-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:18.4414033-04:00",
  "level": "Error",
  "thread": 8,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_Addon()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_UpdateFileID()",
      "Curse.Games.Minecraft.MinecraftGameInstance.get_UpdateAvailable()",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:32:18.4447639-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:32:23.4682874-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #2 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:32:24.3348229-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:24.3406296-04:00",
  "level": "Info",
  "thread": 13,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:26.3352249-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network address has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:26.3365488-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network status changed: Disconnected"
},
{
  "timestamp": "2025-06-12T12:32:26.4568152-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:26.6064723-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:28.1999627-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:28.4063251-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:28.4379092-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected, but internet not available. Waiting for connection"
},
{
  "timestamp": "2025-06-12T12:32:28.4379777-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network status changed: Reconnecting"
},
{
  "timestamp": "2025-06-12T12:32:28.580655-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network address has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:28.5998191-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected, but internet not available. Waiting for connection"
},
{
  "timestamp": "2025-06-12T12:32:28.751225-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:28.9427397-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:28.9427566-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network status changed: Connected"
},
{
  "timestamp": "2025-06-12T12:32:33.6156939-04:00",
  "level": "Error",
  "thread": 8,
  "memory": 0.0,
  "message": "Failed to get addon from service!",
  "error": {
    "message": "One or more errors occurred. (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError) (Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError)",
    "type": "System.AggregateException",
    "stack": [
      "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)",
      "Curse.Radium.Addons.ProjectRepository.FetchProjectWithRetries(Int32)",
      "Curse.Radium.Addons.ProjectRepository.UpdateProject(Int32)",
      "Curse.Radium.Addons.ProjectRepository.GetProjectById(Int32,Boolean)",
      "Curse.AppService.Minecraft.MinecraftInstanceMapper.Map(MinecraftGameInstance)",
      "System.Linq.Enumerable+SelectEnumerableIterator`2.MoveNext()",
      "System.Linq.Enumerable+WhereEnumerableIterator`1.ToArray()",
      "Curse.Plugin.API.Handlers.Minecraft.GameInstance.MinecraftGetInstancesRequestHandler.HandleRequest(MinecraftGetInstancesRequest,CancellationToken)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0+<<Handle>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.API.Handlers.AsyncApiRequestHandlerBase`1+<>c__DisplayClass7_0.<Handle>b__0()",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()",
      "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)",
      "System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&)",
      "Curse.Plugin.RequestExecutor+<>c__DisplayClass9_0.<ExecuteAsync>b__0()",
      "System.Threading.Tasks.Task`1.InnerInvoke()",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&,Thread)",
      "System.Threading.Tasks.Task.ExecuteEntry()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+ConcurrentExclusiveTaskScheduler.ExecuteTask(Task)",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks()",
      "System.Threading.Tasks.ConcurrentExclusiveSchedulerPair+SchedulerWorkItem.System.Threading.IThreadPoolWorkItem.Execute()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(PortableThreadPool,Boolean&)",
      "System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()",
      "System.Threading.Thread+StartHelper.RunWorker()",
      "System.Threading.Thread+StartHelper.Run()",
      "System.Threading.Thread.StartCallback()"
    ],
    "innerError": {
      "message": "Failed getting project 1258033. Status Code: InternalServerError. Exception: System.Net.WebException: Web Service responded with failure status code: InternalServerError",
      "type": "Curse.Server.Communication.Exceptions.ServerRequestException",
      "stack": [
        "Curse.TechService.AddonServiceClient.HandleResponse[T](ServiceResponse`1,Func`1)",
        "Curse.TechService.AddonServiceClient.GetProject(Int32)",
        "Curse.Radium.Addons.ProjectRepository+<>c__DisplayClass31_0.<FetchProjectWithRetries>b__0()",
        "Curse.Radium.Utilities.Retry.Do[T](Func`1,IRetryStrategy,String,Func`2)"
      ]
    }
  }
},
{
  "timestamp": "2025-06-12T12:32:33.6188283-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 2 on InstalledAddonDatabase -> FetchAddonWithRetries"
},
{
  "timestamp": "2025-06-12T12:32:35.4881254-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Validating Minecraft installation"
},
{
  "timestamp": "2025-06-12T12:32:35.4881514-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "/home/avery/Documents/curseforge/minecraft/Install/minecraft-launcher found."
},
{
  "timestamp": "2025-06-12T12:32:39.878613-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:39.8837265-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:32:48.8460293-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:32:48.8505033-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:03.5306177-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:03.625652-04:00",
  "level": "Info",
  "thread": 16,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:11.4412816-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:11.4488319-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:13.9167413-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Checking for updates on first load for modpack e"
},
{
  "timestamp": "2025-06-12T12:33:13.9261547-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Pre-Fetching latest files for instance: e"
},
{
  "timestamp": "2025-06-12T12:33:13.9305318-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Attempt #1 of 3 on InstalledAddonDatabase -> GetAddons"
},
{
  "timestamp": "2025-06-12T12:33:21.3616749-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:21.4557917-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:26.656267-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:26.7213095-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:28.83761-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Curse Mods Agent is shutting down"
},
{
  "timestamp": "2025-06-12T12:33:28.8379551-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Shutting down periodic tasks"
},
{
  "timestamp": "2025-06-12T12:33:28.8382904-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Disabling periodic timers"
},
{
  "timestamp": "2025-06-12T12:33:28.8396169-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[InstallTaskManager] Install Manager Shutting Down"
},
{
  "timestamp": "2025-06-12T12:33:28.8401317-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[InstallTaskManager] Install Manager Shutting Down"
},
{
  "timestamp": "2025-06-12T12:33:28.8401368-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[InstallTaskManager] Install Manager Shutting Down"
},
{
  "timestamp": "2025-06-12T12:33:28.8404301-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Shutdown game instances."
},
{
  "timestamp": "2025-06-12T12:33:28.8458219-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[MinecraftGameInstance] GameInstance.SaveInstancesToDisk: Saving MinecraftGameInstance DB with 2 items"
},
{
  "timestamp": "2025-06-12T12:33:32.6865485-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:32.7429465-04:00",
  "level": "Info",
  "thread": 10,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:49.484151-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:49.5392621-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:52.976086-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:52.9815845-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:33:58.1029619-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:33:58.1336838-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:34:04.6809975-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:34:04.6915751-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:34:08.8064658-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network availability has changed. Checking connection"
},
{
  "timestamp": "2025-06-12T12:34:08.8990313-04:00",
  "level": "Info",
  "thread": 14,
  "memory": 0.0,
  "message": "Network connected and internet available"
},
{
  "timestamp": "2025-06-12T12:34:09.6244841-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[MinecraftGameInstance] GameInstance.SaveInstancesToDisk: Saved MinecraftGameInstance DB, which took 40778ms"
},
{
  "timestamp": "2025-06-12T12:34:09.6249415-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[AddonGameInstance] GameInstance.SaveInstancesToDisk: Saving GameInstance DB with 0 items"
},
{
  "timestamp": "2025-06-12T12:34:10.0701742-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "[AddonGameInstance] GameInstance.SaveInstancesToDisk: Saved GameInstance DB, which took 445ms"
},
{
  "timestamp": "2025-06-12T12:34:10.0897933-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Clearing Discord presence."
},
{
  "timestamp": "2025-06-12T12:34:10.0930265-04:00",
  "level": "Info",
  "thread": 8,
  "memory": 0.0,
  "message": "Discord RPC client disposed successfully."
},
{
  "timestamp": "2025-06-12T12:34:10.8053907-04:00",
  "level": "Info",
  "thread": 15,
  "memory": 0.0,
  "message": "Web Socket session disconnected"
},
{
  "timestamp": "2025-06-12T12:34:10.8075999-04:00",
  "level": "Warn",
  "thread": 15,
  "memory": 0.0,
  "message": "Client disconnected from server"
},
{
  "timestamp": "2025-06-12T12:34:11.0349719-04:00",
  "level": "Warn",
  "thread": 5,
  "memory": 0.0,
  "message": "Parent process is no longer active. Mods Agent will shutdown."
},
{
  "timestamp": "2025-06-12T12:34:11.0352977-04:00",
  "level": "Warn",
  "thread": 1,
  "memory": 0.0,
  "message": "Parent process exit. Shutting down..."
},
{
  "timestamp": "2025-06-12T12:34:11.0493094-04:00",
  "level": "Info",
  "thread": 2,
  "memory": 0.0,
  "message": "Shutting down the logger"
},
{
  "timestamp": "2025-06-12T12:34:11.0760311-04:00",
  "level": "Info",
  "thread": 2,
  "memory": 0.0,
  "message": "Logging worker finished"
}
]}
